title: Il Risveglio A Se Stessi

url: http://ilrisveglioasestessi.it
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:categories/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Meditazione Attiva
   url: /blog/meditazione-attiva
 - title: Naturopatia Tibetana
   url: /blog/naturopatia-tibetana
 - title: Calendario Eventi
   url: /calendario-eventi
 - title: Chi Siamo
   url: /about

social:
   facebook: roby.potocniak
   email: info@gilrisveglioasestessi.it

google_analytics: "UA-62267965-1"
default_locale: "it"
